### PR TITLE
#65: Updated documentation and fixed some wrong values

### PR DESCRIPTION
**Pull request by garretwilson**
There are just basically comment updates to verify the code and bring it up to speed with the latest UCUM spec. I think a few values were corrected as well.

### CODE REVIEW

**Comment by keilw** [comment]
Worked for most parts. It seems the number of units was reduced a bit, so please keep an eye on `NUM_OF_UNITS` in `SystemOfUnitsServiceTest`.

**Comment by garretwilson** [comment]
> It seems the number of units was reduced a bit...

I don't understand. I believe that @magno just tidied up the comments and fixed some typos in the values.

I'm looking at the pull request. Which unit(s) are you saying was/were removed?

**Comment by keilw** [comment]
I cannot see any unit removed as such. Have to see, if e.g. `addUnit()` calls (which affect that number) changed. There is certainly a problem between `LIGNE `and `LINGE `in `SymbolMap`, will check on that now.

**Comment by magnonasc** [comment]
Sorry about that, I just noticed that the command to build the project succeds even with a lot of errors, if I knew it I'd pay more attention to at least point the exactly cause of the errors on #65.

**Comment by keilw** [comment]
It is fixed now, not worries. I will take a look at some other issues like https://github.com/unitsofmeasurement/uom-se/issues/145, so ideally a Systems 0.7 release should be based on uom-se 1.0.5 already.

**Pull request merged**
