### PR TITLE
Deprecate Imperial.OUNCE_LIQUID, add Imperial.FLUID_OUNCE

### LINKED ISSUE #113: Rename OUNCE_LIQUID in Imperial
The `OUNCE_LIQUID` constant in `Imperial` differs from `USCustomary` and the description in
https://en.wikipedia.org/wiki/Imperial_units

Let's call it the same and according to common practice.
Deprecating the old version at least till a 0.8 or higher version.

### PR DESCRIPTION
**Pull request by Kyle-Falconer**
Resolves #113

### CODE REVIEW

**Comment by keilw** [comment]
Thanks. It's a relatively small change, but because projects like Eclipse SmartHome or others use the JSR and extension modules like this one, would you be willing to sign the ECA? https://eclipse.org/legal/ECA.php

**Comment by Kyle-Falconer** [comment]
Signed (shows as pending on the Eclipse site)

**Comment by keilw** [comment]
Great, thanks. What's your Eclipse portal id to see when it's done? If you don't like to share it here, feel free to send me a mail instead.

**Comment by keilw** [comment]
Did it explicitly and also in systems-common-java8/Imperial.

**Pull request closed without merging**
