### PR TITLE
#59: Implemented most of the level units defined on UCUM

### PR DESCRIPTION
**Pull request by magnonasc**
As I mentioned somewhere, the problem with this one is with the `PH` unit, where the compiler don't let me transform `mol/L` in a `Dimensionless` unit, we'll have to find a solution for this one

### CODE REVIEW

**Comment by garretwilson** [comment]
Sorry I haven't kept up with the details here. What's the problem exactly? You don't plan on leaving pH out, do you?

**Comment by keilw** [comment]
No it's simply the question if UCUM (and users) consider it `Dimensionless` or would prefer an actual quantity like `Acidity`, etc.?

**Comment by garretwilson** [comment]
Oh, OK, I understand.

**Comment by magnonasc** [comment]
@garretwilson In UCUM they give us a tip for the type of `Ph`:
> Usually the pH value is considered a dimensionless quantity.

And that's what I tried to do, but the compiler doesn't let us convert from `mol/L` to `Dimensionless`, that's why we're considering to create an `Acidity` unit for that. but I just don't know if the UCUM is restricting us to use `Dimensionless` by that paragraph or if it's giving us some freedom to create that `Acidity` unit type.

**Comment by garretwilson** [comment]
Can you give me more information on what problem the compiler is having, and maybe I can give you some tips.

**Comment by keilw** [comment]
Ok thanks, then let's use whatever works best. The build does not break (according to a CircleCI preview above it also won't if this is merged) but if there was a problem to handle results of operations, we could introduce additional quantities. "is usually" means it is often the case but not that it must be always of type X like e.g. `METRE` is always `Length` in the universe we know.

**Comment by magnonasc** [comment]
Actually I was wrong, the compiler error was with another units, the problem with this one is a typecasting:
```
Caused by: java.lang.ClassCastException: The unit: [mol/m³?] is not compatible with quantities of type interface javax.measure.quantity.Dimensionless
```

**Comment by magnonasc** [comment]
Heey @keilw, is it normal to have a `?` after the type, as in `[mol/m³?]`? It seems that something is not okay here.

**Comment by garretwilson** [comment]
So `ClassCastException` can occur because you actually tried to make an incorrect cast, or the code could through it manually. Without looking at the code, and only looking at the message, I would make a bet that the underlying `uom-systems` code (or one of its dependencies) somewhere is manually checking and throwing this exception, not Java. So in other words, `uom-systems` has created the (reasonable) restriction that this unit is not dimensionless by definition. I don't know what JSR-363 says, but I would guess this is just a `uom-systems` check to make sure you don't define something incorrectly. You could make it more lenient, or do one of these workaround you guys were already talking about.

I'll let you guys decide what to do with this runtime problem. If you run into tough compiler problems, though, let me know and maybe I can come up with ideas.

**Comment by keilw** [comment]
E.g. we created some custom quanties in https://github.com/unitsofmeasurement/uom-domain/tree/master/health/health-api (the module name was inspired by Agorava, maybe there could be a "domain-quantity" one in future or a "health-quantity"?) So if there is a benefit it can always be created. For cases that do fine with `Dimensionless` I would not create it just for the sake of it.

**Comment by keilw** [comment]
@magnonasc That usually means the exact string cannot be found in the `SymbolMap`/Resource bundles

**Comment by magnonasc** [comment]
So, if we have to create a quantity in other api this is ready to merge, the `PH` is in a block of comments, it won't cause any trouble at the moment. I'll just create another issue just to that unit

**Pull request merged**
