### PR TITLE
Correct units on BEL_WATT and BEL_KILOWATT

### PR DESCRIPTION
**Pull request by geekmug**
This looks like a copy/paste mistake (from the lines above).

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/uom-systems/119)

### CODE REVIEW

**Comment by keilw** [comment]
@geekmug, @dautelle, @desruisseaux please see the issue ticket. We cannot extend the UCUM system module with units the UCUM standard does not yet include. Please let's find a different module, i.E. "Energy". And feel free to recommend hat unit to the UCUM group as well. It may take a long time or they could never include it, if their stakeholders do not consider it important enough.

**Comment by maximelefrancois86** [comment]
Aren't these units already part of the UCUM standard ? 

cf http://unitsofmeasure.org/ucum.html#para-46

**Comment by keilw** [comment]
BELWATT and -KILOWATT it seems. Although the UCUM system is currently not used at Eclipse directly (UOMo UCUM is at most complimentary, it uses the UCUM XML directly in a late-binding manner) would you be happy to sign the ECA?

**Comment by geekmug** [comment]
@keilw Is this an Eclipse Foundation project? If you are going to gate contributions to this project based on an ECA, then I would suggest you add a CONTRIBUTING.md to this project explaining the situation, because I had to google what UOMo is and I still don't understand how it relates to my contribution. I would not have submitted a pull request, because the time and energy required to carefully read and accept the terms of a legal agreement dwarfs the amount of time and energy that was required to edit the two lines of code (or simplify add two lines to my project to define the unit locally).

**Comment by geekmug** [comment]
This project has a BSD 3-clause, so nothing will stop you from linking against this project as part of an Eclipse Foundation project. If you decide to copy code directly, then you as the contributor to an Eclipse Foundation project would be obligated to certify that you have the right to submit it. Again, I can't see how any of that has anything to do with my contribution to this project. I have no interest in entering into a legal agreement with the Eclipse Foundation (or any other entity) that opens me up to future legal proceedings without compensation. I provided my contribution on the same terms that this project provides its source code to me (and everyone else).

I've closed the pull request. You can consider it a bug report and create your own original work. Good luck with your project.

**Comment by keilw** [comment]
Neither Eclipse nor Apache Foundation nor the JCP accept contributions without signing an agreement. Thanks for closing the PR, I'll also close https://github.com/unitsofmeasurement/uom-systems/issues/120 because it is a duplicate of https://github.com/unitsofmeasurement/uom-systems/issues/59

**Comment by geekmug** [comment]
You are free to place whatever hurdles you want in order to accept contributions, but I asked if this was an Eclipse Foundation project and you said no. Is this an Apache Foundation project? I suspect not. In which case, there is no legal reasoning here -- it's just confusion.

**Comment by keilw** [comment]
Eclipse projects whether Science, LocationTech, SmartHome, MicroProfile or upcoming new Jakarta EE are among the biggest downstream users. And to be accepted in Eclipse Orbit all contributions need to be vetted and contributors should either have signed the JSPA or JCP Associate Agreement or similar agreements like the ECA to ensure there are no IP conflicts. Since it is widely used (the predecessor still gets nearly 200k downloads on Bintray in a 12 month period, V1 of the API also gets more and more downloads, they pretty much tripled compared to the previous year) including commercial products, we ensure, users do not get nasty surprises or lawsuits. Like everyone else.

**Pull request closed without merging**
